export { ReactComponent as CartSVG } from './icons/cart.svg'
export { ReactComponent as Cart2SVG } from './icons/cart2.svg'
export { ReactComponent as ParachuteSVG } from './icons/parachute.svg'
export { ReactComponent as XIconSVG } from './icons/xIcon.svg'
export { ReactComponent as ChevronLeftSVG } from './icons/chevronLeft.svg'
export { ReactComponent as ChevronRightSVG } from './icons/chevronRight.svg'
export { ReactComponent as Logo } from './icons/logo.svg'
